{
 "title": "CEPH OVERVIEW",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of Monitors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "type_instance.keyword: number and plugin_instance.keyword: mon",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Monitors in Quorum",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "type_instance.keyword: quorum and plugin_instance.keyword: mon",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "#  OSD UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "type_instance.keyword: up and plugin_instance.keyword: osd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "#  OSD IN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "type_instance.keyword: in and plugin_instance.keyword: osd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "#  OSD DOWN",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "type_instance.keyword: down and plugin_instance.keyword: osd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "#  OSD OUT",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "type_instance.keyword: out and plugin_instance.keyword: osd",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "WRITE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type_instance.keyword: write_op_per_sec",
     "timeField": "@timestamp"
    },
    {
     "alias": "READ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type_instance.keyword: read_op_per_sec",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "THROUGHPUT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "READ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*8",
       "meta": {},
       "settings": { "script": { "inline": "_value*8" } },
       "type": "sum"
      }
     ],
     "query": "plugin_instance.keyword: * AND type_instance.keyword: read_bytes_sec",
     "timeField": "@timestamp"
    },
    {
     "alias": "WRITE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*8",
       "meta": {},
       "settings": { "script": { "inline": "_value*8" } },
       "type": "sum"
      }
     ],
     "query": "plugin_instance.keyword: * AND type_instance.keyword: write_bytes_sec",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RADOS BENCH LATENCY FOR SSD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "MAX",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: ssd_max_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "MIN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: ssd_min_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "AVG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: ssd_avg_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "STD DEV",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: ssd_stddev_latency",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "RADOS BENCH LATENCY FOR HDD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "MAX",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: hdd_max_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "MIN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: hdd_min_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "AVG",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: hdd_avg_latency",
     "timeField": "@timestamp"
    },
    {
     "alias": "STD DEV",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: hdd_stddev_latency",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD APPLY LATENCY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance: osd AND type_instance.keyword: apply_latency_ms",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD COMMIT LATENCY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance: osd AND type_instance.keyword: commit_latency_ms",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD STATUS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UP",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: osd AND type_instance.keyword: up",
     "timeField": "@timestamp"
    },
    {
     "alias": "IN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: osd AND type_instance.keyword: in",
     "timeField": "@timestamp"
    },
    {
     "alias": "DOWN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "plugin_instance.keyword: osd AND type_instance.keyword: down",
     "timeField": "@timestamp"
    },
    {
     "alias": "OUT",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "min"
      }
     ],
     "query": "plugin_instance.keyword: osd AND type_instance.keyword: out",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD USAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "plugin_instance: osd AND type_instance.keyword: kb_used",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CAPACITY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "AVAIL",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: total_avail",
     "timeField": "@timestamp"
    },
    {
     "alias": "CAPACITY",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: total_space",
     "timeField": "@timestamp"
    },
    {
     "alias": "USED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: cluster AND type_instance.keyword: total_used",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD CAPACITY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "plugin_instance: osd AND type_instance.keyword: kb_total",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}