{
 "title": "OSD Disk Performance",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "zula209, zula210, zula211, zula212"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD DISK READ IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "12" },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "disk", "query": "dev_sd*" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read",
       "hide": true,
       "id": "1",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_ops AND host.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD DISK READ THROUGHPUT",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "12" },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "disk", "query": "dev_sd*" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read",
       "hide": true,
       "id": "1",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_octets AND host.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD DISK WRITE IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "12" },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "disk", "query": "dev_sd*" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write",
       "hide": true,
       "id": "1",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_ops AND host.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD DISK WRITE Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "plugin_instance.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "12" },
       "type": "terms"
      },
      {
       "fake": true,
       "id": "5",
       "query": "*",
       "settings": {
        "filters": [
         { "label": "disk", "query": "dev_sd*" }
        ]
       },
       "type": "filters"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write",
       "hide": true,
       "id": "1",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_octets AND host.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD nVM-e WRITE IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write",
       "hide": true,
       "id": "1",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_ops AND host.keyword: $host AND plugin_instance.keyword: dev_nvme0n1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD nVM-e WRITE Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "write",
       "hide": true,
       "id": "1",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_octets AND host.keyword: $host AND plugin_instance.keyword: dev_nvme0n1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD nVM-e READ IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read",
       "hide": true,
       "id": "1",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_ops AND host.keyword: $host AND plugin_instance.keyword: dev_nvme0n1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSD nVM-e READ Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "read",
       "hide": true,
       "id": "1",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "1",
       "id": "3",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: disk AND collectd_type.keyword: disk_octets AND host.keyword: $host AND plugin_instance.keyword: dev_nvme0n1",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}