{
 "title": "OSD HOSTS STATS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "zula209, zula210, zula211, zula212"
   }
  ]
 },
 "panels": [
  {
   "title": "$host RX/TX PPS for 40G Interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "avg interface pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "4",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "5",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "4",
       "id": "6",
       "meta": {},
       "pipelineAgg": "4",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "5",
       "id": "7",
       "meta": {},
       "pipelineAgg": "5",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_packets AND plugin_instance.keyword: enp131s0f0",
     "timeField": "@timestamp"
    },
    {
     "alias": "max error pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "3",
       "id": "5",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_errors AND plugin_instance.keyword: enp131s0f0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host RX/TX Throughput for 40G Interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "avg interface pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "4",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "5",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "4",
       "id": "6",
       "meta": {},
       "pipelineAgg": "4",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "5",
       "id": "7",
       "meta": {},
       "pipelineAgg": "5",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_octets AND plugin_instance.keyword: enp131s0f0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host RX/TX PPS for 10G Interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "avg interface pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "4",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "5",
       "inlineScript": "_value/60",
       "meta": {},
       "settings": { "script": { "inline": "_value/60" } },
       "type": "max"
      },
      {
       "field": "4",
       "id": "6",
       "meta": {},
       "pipelineAgg": "4",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "5",
       "id": "7",
       "meta": {},
       "pipelineAgg": "5",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_packets AND plugin_instance.keyword: ens4f0",
     "timeField": "@timestamp"
    },
    {
     "alias": "max error pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "max"
      },
      {
       "field": "1",
       "id": "4",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "3",
       "id": "5",
       "meta": {},
       "pipelineAgg": "3",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_errors AND plugin_instance.keyword: ens4f0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host RX/TX Throughput for 10G Interface",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "avg interface pps",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rx",
       "hide": true,
       "id": "4",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "tx",
       "hide": true,
       "id": "5",
       "inlineScript": "(_value*8)/60",
       "meta": {},
       "settings": { "script": { "inline": "(_value*8)/60" } },
       "type": "max"
      },
      {
       "field": "4",
       "id": "6",
       "meta": {},
       "pipelineAgg": "4",
       "settings": {},
       "type": "derivative"
      },
      {
       "field": "5",
       "id": "7",
       "meta": {},
       "pipelineAgg": "5",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "plugin.keyword: interface AND host.keyword: $host AND collectd_type.keyword: if_octets AND plugin_instance.keyword: ens4f0",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host MEMORY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "FREE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.keyword: $host AND collectd_type.keyword: memory AND type_instance.keyword: free",
     "timeField": "@timestamp"
    },
    {
     "alias": "USED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.keyword: $host AND collectd_type.keyword: memory AND type_instance.keyword: used",
     "timeField": "@timestamp"
    },
    {
     "alias": "BUFFERED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.keyword: $host AND collectd_type.keyword: memory AND type_instance.keyword: buffered",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "host.keyword: $host AND collectd_type.keyword: memory AND type_instance.keyword: cached",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$host LOAD",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "longterm",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "midterm",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "avg"
      },
      {
       "field": "shortterm",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "collectd_type.keyword: load AND host.keyword: $host",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}