{
 "title": "Pool Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "pool", "label": "Pool", "query": "pool-rbdhdd, pool-rbdssd" },
   { "name": "cluster", "label": "cluster", "query": "ceph-ceph" }
  ]
 },
 "panels": [
  {
   "title": "USED SPACE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: bytes_used",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: objects",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PG_NUM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: pg_num",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "PGP_NUM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: pgp_num",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "IOPS per POOL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "READ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: read_op_per_sec",
     "timeField": "@timestamp"
    },
    {
     "alias": "WRITE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: write_op_per_sec",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "READ",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*8",
       "meta": {},
       "settings": { "script": { "inline": "_value*8" } },
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: read_bytes_sec",
     "timeField": "@timestamp"
    },
    {
     "alias": "WRITE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "value",
       "id": "1",
       "inlineScript": "_value*8",
       "meta": {},
       "settings": { "script": { "inline": "_value*8" } },
       "type": "avg"
      }
     ],
     "query": "plugin_instance.keyword: $pool AND type_instance.keyword: write_bytes_sec",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}